### ISSUE TITLE
"global name '_' is not defined" in v.py, kombilo.py, and kombiloNG.py

### ISSUE THREAD

**Issue by y-ich** [ugoertz/kombilo#2] opened 2017-03-10 23:45 UTC
Under the following environment, kombilo can not start and outputs errors "global name '_' is not defined" in v.py, kombilo.py, and kombiloNG.py.

OS: macOS 10.12.3
python: 2.7.13
lang: ja_JP.UTF-8

I could avoid these errors by putting a line "_ = gettext.gettext" (and "import gettext" if necessary) in these files.
But this workaround seems not right since you may expect _ in builtins.__dict__.

**Comment by ugoertz** [comment] 2017-03-12 20:10
Since I cannot reproduce this problem ('_' is inserted as a dummy function into builtins.dict at the very beginning of kombilo.py, so I currently do not understand how it could be undefined), could you give me some further information?

Did you install Kombilo via pip, or in a different way? Is it the version from PyPI (Kombilo 0.8.4), or from the master branch of the repository?

Could you paste the full traceback when starting kombilo in a terminal?

Thank you!

**Comment by y-ich** [comment] 2017-03-13 00:24
About environment, I am using HomeBrew Python 2.7.13.

About installation,

    pip install git+https://github.com/ugoertz/kombilo.git

About output of kombilo,
when I run kombilo in a terminal, kombilo outputs nothing.
And kombilo outputs ~/.kombilo/08/kombilo.err.

    Traceback (most recent call last):
      File "/usr/local/bin/kombilo", line 11, in <module>
        load_entry_point('kombilo==0.8.4', 'gui_scripts', 'kombilo')()
      File "/usr/local/lib/python2.7/site-packages/kombilo/kombilo.py", line 3697, in run
        app = App(root)
      File "/usr/local/lib/python2.7/site-packages/kombilo/kombilo.py", line 3284, in __init__
        v.Viewer.__init__(self, master, BoardWC, DataWindow)
      File "/usr/local/lib/python2.7/site-packages/kombilo/v.py", line 2955, in __init__
        self.initButtons(navFrame, labelFrame)
      File "/usr/local/lib/python2.7/site-packages/kombilo/v.py", line 2668, in initButtons
        lab = Label(navFrame, text=_('Ctrl-Click:'))
    NameError: global name '_' is not defined

If you will resolve the error in v.py, you will encounter a same error in kombilo.py, and kombiloNG.py sequentially.

Yes, I saw the following code,

    if '_' not in builtins.__dict__:
        builtins.__dict__['_'] = lambda s: s

in kombilo.py, and

    if not '_' in builtins.__dict__:
        # print 'kombiloNG ignores translations'
        _ = lambda s: s

, so I felt something strange and I imagined that you may be puzzled...

If this issue happens only in my environment, it is ok, my workaround works well now.
Thank you!

**Comment by ugoertz** [comment] 2017-03-19 20:38
I just checked in a change to the master branch which hopefully fixes this issue by setting the language to "en" if it is not set yet. Please do complain if this does not solve the issue for you.

However, I think that the problem you have been experiencing above might have been caused by something else: There seems to be a mix-up of different kombilo versions living on your system(?) - in the traceback you quoted, the startup script (line 3) seems to refer to a Kombilo 0.8.4 version, but you wanted to call the master branch. I am not really sure what could cause this ... are you installing kombilo in a virtualenv, or system-wide?

(I suspect that if Kombilo is installed "directly" (i.e., without virtualenv) and at the same time inside a virtualenv, then one has to be careful because even from the virtualenv the other starting script could come earlier in the PATH.)

**Comment by y-ich** [comment] 2017-03-20 00:00
Thank you for your fix.
Unfortunately it did not solved the issue.

When kombilo is invoked, calling self.swtich_language at line 2852 in v.py calls an overriding App#switch_languange rather than Viwer#switch_language.
And App#switch_languange calls App#untranslate_cont_sort_crit before calling Viewer#switch_language, which will define the function '_'.
But App#untranslate_cont_sort_crit uses the function '_' before it will be defined.

I am using a plain HomeBrew Python without virtualenv.
pip seems to generate /usr/local/bin/kombilo as entry point.
Sorry, since I am not familiar with Python and pip, it may be no information for you...
I definitely agree that my Python environment (HomeBrew Python and Python3) always has troubles!^^;

**Closed as completed** 2017-03-20 19:46 UTC

**Comment by ugoertz** [comment] 2017-03-20 19:48
OK, I see, thanks! ... I hope it works now.
